{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "name" : "categories",
  "children" : [ {
    "name" : "Product defects",
    "children" : [ {
      "name" : "  Expected: No Exception to be thrown\r\n  But was:  <System.Exception: I'm an exception\r\n   at AllureSample.Sample_AllureReportTypes.TestClass.<>c.<SimpleTestFailed>b__3_0() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 54\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>\r\n",
      "children" : [ {
        "name" : "SimpleTestFailed",
        "uid" : "154b2ebd5d6156d8",
        "parentUid" : "6146b6af85bac28af2dbe3116862e177",
        "status" : "failed",
        "time" : {
          "start" : 1569925991132,
          "stop" : 1569925991208,
          "duration" : 76
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "6146b6af85bac28af2dbe3116862e177"
    } ],
    "uid" : "8fb3a91ba5aaf9de24cc8a92edc82b5d"
  } ]
}